package com.example.mobile_native.network

import com.example.mobile_native.model.Book

class ValidateSyncedObject {

    /**
     * Static method. Checks if the object has a database id or one generated by us to tell if the object
     * exists on the server.
     * OUT: true - if object exists on the server
     * false - if it exists only in local database and has the id with an anomalous form
     */
    companion object {
        fun checkSyncedObject(model: Book): Boolean {
            if (model.id!!.length >= 4)
                return true
            return false
        }
    }
}